version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - app-network

  # Include this if not using Supabase's hosted PostgreSQL
  # postgres:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=ewas
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  # postgres-data: 