[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["client/src/**", "server/**"]

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production" 